### ISSUE TITLE
Machine Learning Projects

### ISSUE THREAD

**Issue by geetika001** [Khushii-Arora/SmallWorkingProjects_Hacktoberfest22#104]
add ml project based on fake news detection

**Comment by geetika001** [comment]
Hey @Khushii-Arora can I add the above ml project in this repo under Hacktoberfest??

**Comment by ranshu1601** [comment]
Hello Khushi can i work on this issue ? regarding hacktoberfest .

**Comment by geetika001** [comment]
#110 
@Khushii-Arora I have added this Project in the PR.Please review and consider for Hacktoberfest.It is a detailed project containing ML models and a little of data visualization as well.Will help a lot of students working on such projects.
